language: swift
osx_image: xcode11.1

cache: bundler

jobs:
  include:
  - stage: test
    name: "Running unit tests"
    script: bundle exec fastlane unit_test device:'iPhone 8' ios_version:'13.1'
    after_success: bundle exec slather

  - stage: test
    name: "Running UI tests"
    script: bundle exec fastlane ui_test device:'iPhone 8' ios_version:'13.1'
    after_success: bundle exec slather

stages:
- name: test
  if: (type = pull_request OR type = push) AND (branch = master OR branch = develop)
